version: "3.3"

services:
  homeworkapp:
    image: stibi/prusa-homework:latest
    ports:
      - "5000"
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - homeworkapp
    ports:
      - "4000:4000"
  redis:
    image: redis:6.2.1
    ports:
      - "6379:6379"
