---
- name: homeworkapp envfile with configuration
  ansible.builtin.template:
    src: homeworkapp_envfile.j2
    dest: /etc/default/homeworkapp
    mode: '0644'

- name: copy homework app systemd service
  ansible.builtin.copy:
    src: homeworkapp.service
    dest: /etc/systemd/system/homeworkapp.service
    mode: 0644
  notify: reload systemd

- name: make sure homework app is up and running
  ansible.builtin.service:
    name: homeworkapp
    state: started
    enabled: true

- name: initialize db in case it is not
  run_once: true
  block:
    - name: check if app db is initialized
      delegate_to: "{{ groups['db_server'][0] }}"
      become: yes
      become_user: postgres
      community.postgresql.postgresql_query:
        db: "{{ homeworkapp_db_name }}"
        query: SELECT 1 from palindrom;
  rescue:
    - name: initialize app database
      command: docker exec -ti homeworkapp.service sh -c 'python create_db.py'
