---
- name: Check if dev user exist already
  delegate_to: "{{ groups['db_server'][0] }}"
  run_once: true
  become: yes
  become_user: postgres
  community.postgresql.postgresql_query:
    query: SELECT 1 FROM pg_roles WHERE rolname='dev';
  register: dev_user_exist

- name: Create dev user
  delegate_to: "{{ groups['db_server'][0] }}"
  run_once: true
  become: yes
  become_user: postgres
  community.postgresql.postgresql_query:
    query: CREATE USER dev WITH ENCRYPTED PASSWORD %(dev_db_user_password)s;
    named_args:
      dev_db_user_password: "{{ dev_db_user_password }}"
  when: dev_user_exist.rowcount == 0 

- name: Grant permissions to dev user
  delegate_to: "{{ groups['db_server'][0] }}"
  run_once: true
  become: yes
  become_user: postgres
  community.postgresql.postgresql_query:
    db: "{{ homeworkapp_db_name }}"
    query: "GRANT SELECT ON palindrom TO dev;"
