#   # TODO use app user and app directory
- name: Copy compose source files
  ansible.builtin.copy:
    src: "{{ item }}"
    # dest: "{{ docker_compose_dir }}"
    dest: /root/
    mode: 0600
  with_items:
    - docker-compose.yml
    - nginx.conf

- name: Create and start services
  community.docker.docker_compose:
    project_name: homework
    project_src: /root/
    build: no
    pull: yes
    recreate: always
    restarted: yes
    scale:
      homeworkapp: 2
  register: output

# - ansible.builtin.debug:
#     var: output
