#   # TODO use app user and app directory
- name: Copy compose source templates
  ansible.builtin.copy:
    src: docker-compose.yml
    # dest: "{{ docker_compose_dir }}"
    dest: /root/
    mode: 0600

# - name: Tear down existing services
#   community.docker.docker_compose:
#     project_src: flask
#     state: absent

- name: Create and start services
  community.docker.docker_compose:
    project_name: homework
    project_src: /root/
  register: output

- ansible.builtin.debug:
    var: output

# - name: Run `docker-compose up` again
#   community.docker.docker_compose:
#     project_src: flask
#     build: no
#   register: output

# - ansible.builtin.debug:
#     var: output

# - ansible.builtin.assert:
#     that: "not output.changed "

# - name: Stop all services
#   community.docker.docker_compose:
#     project_src: flask
#     build: no
#     stopped: yes
#   register: output

# - ansible.builtin.debug:
#     var: output

# - ansible.builtin.assert:
#     that:
#       - "not web.flask_web_1.state.running"
#       - "not db.flask_db_1.state.running"

# - name: Restart services
#   community.docker.docker_compose:
#     project_src: flask
#     build: no
#     restarted: yes
#   register: output

# - ansible.builtin.debug:
#     var: output

# - ansible.builtin.assert:
#     that:
#       - "web.flask_web_1.state.running"
#       - "db.flask_db_1.state.running"