---
- name: install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-passlib
    - nginx

- include: nginx.yml
- include: app.yml
- include: db.yml
