---
- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql
    - python3-psycopg2 # to make the community.postgresql.postgresql_db working

- name: make sure postgresql is up and running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: create database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"

- name: Set postgres listen_address
  become: yes
  become_user: postgres
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "localhost,{{ db_server_listen_address }}"
  notify:
    - restart postgres

- name: Grant app and dev access
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/12/main/pg_hba.conf
    contype: host
    users: app,dev
    source: 0.0.0.0/0
    databases: "{{ db_name }}"
    method: md5
    create: true
  notify:
    - restart postgres
