---
- name: Install docker-compose
  get_url: 
    url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64" 
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

# TODO symlink do /bin/ bude potreba
# TODO a nebo proste pouzit docker-compose apt balik!
